# azure-pipeline-destroy.yml
trigger: none # This pipeline should never run automatically

pr: none

variables:
  - name: terraformVersion
    value: '1.5.0'
  - name: workingDirectory
    value: '$(System.DefaultWorkingDirectory)'

pool:
  name: azure-agent001

steps:
  # Checkout the code
  - checkout: self
    displayName: 'Checkout code'

  # Install unzip first
  - script: |
      sudo apt-get update
      sudo apt-get install -y unzip
    displayName: 'Install unzip'

  # Install Terraform
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '$(terraformVersion)'

  # Terraform initialization
  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(workingDirectory)'
      environmentServiceNameAzureRM: 'AzureService'
      backendServiceArm: 'AzureService'
      backendAzureRmResourceGroupName: 'Backend-static-hosting'
      backendAzureRmStorageAccountName: 'tfstate7800'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'

  # Terraform destroy (with plan for safety)
  - task: TerraformTaskV4@4
    displayName: 'Terraform Destroy Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(workingDirectory)'
      environmentServiceNameAzureRM: 'AzureService'
      commandOptions: '-destroy -out=tfdestroyplan'

  # Terraform apply destroy
  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply Destroy'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(workingDirectory)'
      environmentServiceNameAzureRM: 'AzureService'
      commandOptions: '-auto-approve tfdestroyplan'

  # Clean up
  - script: |
      rm -f tfdestroyplan
    displayName: 'Clean up temporary files'
    condition: always()
