trigger:
  - main

pr:
  branches:
    include:
      - main  # Run on PRs targeting main

stages:
  - stage: 'Test_and_Plan'
    jobs:
    - job: 'Terraform'
      pool:
        name: azure-agent001
      steps:
        - checkout: self
        - script: sudo apt-get update && sudo apt-get install -y unzip
        - task: TerraformInstaller@0
          inputs: { terraformVersion: '$(terraformVersion)' }
        - task: TerraformTaskV4@4
          name: terraformInit
          inputs:
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            environmentServiceNameAzureRM: 'AzureService'
        - task: TerraformTaskV4@4
          name: terraformValidate
          inputs:
            command: 'validate'
            workingDirectory: '$(workingDirectory)'
        - task: TerraformTaskV4@4
          name: terraformPlan
          inputs:
            command: 'plan'
            workingDirectory: '$(workingDirectory)'
            environmentServiceNameAzureRM: 'AzureService'
            commandOptions: '-out=tfplan'
        - publish: '$(workingDirectory)/tfplan'
          artifact: tfplan

  - stage: 'Deploy'
    dependsOn: 'Test_and_Plan'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
    - deployment: 'Terraform'
      pool:
        name: azure-agent001
      environment: 'Production' # This allows you to set manual approvals in Azure DevOps
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: tfplan
            - task: TerraformInstaller@0
              inputs: { terraformVersion: '$(terraformVersion)' }
            - task: TerraformTaskV4@4
              inputs:
                command: 'init'
                workingDirectory: '$(workingDirectory)'
                environmentServiceNameAzureRM: 'AzureService'
            - task: TerraformTaskV4@4
              inputs:
                command: 'apply'
                workingDirectory: '$(workingDirectory)'
                environmentServiceNameAzureRM: 'AzureService'
                commandOptions: '-auto-approve tfplan'
            - script: |
                WEB_HOST=$(terraform output -raw primary_web_host)
                echo "##vso[task.setvariable variable=websiteUrl;isOutput=true]$WEB_HOST"
                echo "## Website URL: $WEB_HOST"
